# Generated by Django 5.1 on 2024-08-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_shift"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="shiftType",
        ),
        migrations.AddField(
            model_name="shift",
            name="location",
            field=models.CharField(default="Unknown", max_length=30),
            preserve_default=False,
        ),
    ]
