# Generated by Django 5.1 on 2024-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_shift_shifttype_shift_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="firstName",
            field=models.CharField(default="Wilson", max_length=20),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="firstName",
            field=models.CharField(default="Wilson", max_length=20),
        ),
    ]
